name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup V environment
        uses: nocturlab/setup-vlang-action@v1.1.2
        with:
          v-version: master

      # Build nightly
      - name: Build vlog
        run: v -o vlog-${{matrix.os}} vlog.v
             
      # Upload builds as artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: |
            if [ "${{matrix.os}}" -eq "windows" ]; then
              vlog-${{matrix.os}}.exe
            else
              vlog-${{matrix.os}}
            fi
